RSS Feed downloader
update main script, check parameters, if no parameters are given it'll
download all existing feeds in /srv/http/rss.

small cleanup too

diff --git a/populateRssTemplate b/populateRssTemplate
--- a/populateRssTemplate
+++ b/populateRssTemplate
@@ -1,11 +1,16 @@
 #!/bin/bash
 
+if ! (( $# == 3 )); then
+	echo -e "Invalid amount of parameters!\nUsage: populateRssTemplate {url} {templateFile} {rss feed}"
+	exit
+fi
+
 url="$1"
 id="$(echo $url | sed -E 's|^.*/(.*)$|\1|')"
 templateFile="$2"
 rssFeed="$3"
 
-if ! grep -e "$id" $(pwd)/.archive.txt
+if ! grep -e "$id" "$(pwd)/.archive.txt"
 then
 	formattedTitleUploaderDateString="$(youtube-dl -o '%(title)s;%(uploader)s;%(upload_date)s;%(timestamp)s' --get-filename "$url")"
 	youtube-dl -x --ignore-config --download-archive "$(pwd)"/.archive.txt -o './videos/%(title)s.%(ext)s' "$url"
@@ -19,7 +24,7 @@ then
 	#echo "title is $title, author is $author, pubDate is $pubDate, fileName $fileName, link $link"
 
 	if ! [[ $timeStamp == "NA" ]]; then
-		DISPLAY=:0 notify-send "THERE WAS AN ACTUAL TIMESTAMP: $timestamp"
+		DISPLAY=:0 notify-send "THERE WAS AN ACTUAL TIMESTAMP: $timeStamp"
 	fi
 
 	printf -v escaped "%q\n" "$(youtube-dl --get-description "$url")"
